stages:
  - deploy

update:
  stage: deploy
  script:
    - docker-compose down && docker-compose up
    # 或者
    # - docker run --rm -v `pwd`/settings.json:/app/settings.json waitingsong/gitlab-variable-helper
